# Generated by Django 4.2.13 on 2024-06-17 12:42

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("home", "0007_remove_usersubmission_problem4_rating_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="usersubmission",
            name="problem2_rating",
        ),
        migrations.RemoveField(
            model_name="usersubmission",
            name="problem3_rating",
        ),
    ]
