# Generated by Django 4.2.13 on 2024-06-17 12:49

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("home", "0008_remove_usersubmission_problem2_rating_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="usersubmission",
            name="problem2_rating",
            field=models.CharField(default=0, max_length=5),
            preserve_default=False,
        ),
    ]
