# Generated by Django 4.2.13 on 2024-06-18 12:52

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("home", "0010_remove_usersubmission_problem2_rating"),
    ]

    operations = [
        migrations.AddField(
            model_name="usersubmission",
            name="rating2",
            field=models.CharField(default=0, max_length=5),
            preserve_default=False,
        ),
    ]
