# Generated by Django 4.2.13 on 2024-07-01 07:24

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        (
            "home",
            "0017_rename_error_description_1_usersubmission_error_description_11_and_more",
        ),
    ]

    operations = [
        migrations.RenameField(
            model_name="usersubmission",
            old_name="address",
            new_name="organisation",
        ),
        migrations.AddField(
            model_name="usersubmission",
            name="designation",
            field=models.CharField(default=0, max_length=100),
            preserve_default=False,
        ),
    ]
