# Generated by Django 4.2.13 on 2024-07-23 05:40

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("home", "0018_rename_address_usersubmission_organisation_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="TASubmission",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("ta_logical_error_identification1", models.CharField(max_length=10)),
            ],
        ),
    ]
