# Generated by Django 4.2.13 on 2024-07-29 15:59

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("home", "0022_tasubmission_ta_feedback2_tasubmission_ta_feedback3_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="tasubmission",
            name="designation",
            field=models.CharField(default=0, max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="tasubmission",
            name="email",
            field=models.EmailField(default=0, max_length=254),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="tasubmission",
            name="name",
            field=models.CharField(default=0, max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="tasubmission",
            name="organisation",
            field=models.CharField(default=0, max_length=200),
            preserve_default=False,
        ),
    ]
