# Generated by Django 4.2.13 on 2024-07-31 15:04

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("home", "0024_tasubmission_elapsed_time"),
    ]

    operations = [
        migrations.RenameField(
            model_name="tasubmission",
            old_name="elapsed_time",
            new_name="elapsed_time1",
        ),
    ]
