# Generated by Django 4.2.13 on 2024-07-31 15:32

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("home", "0026_tasubmission_elapsed_time2_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="tasubmission",
            old_name="elapsed_time1",
            new_name="taproblem1_elapsed_time",
        ),
        migrations.RenameField(
            model_name="tasubmission",
            old_name="elapsed_time2",
            new_name="taproblem2_elapsed_time",
        ),
        migrations.RenameField(
            model_name="tasubmission",
            old_name="elapsed_time3",
            new_name="taproblem3_elapsed_time",
        ),
        migrations.RenameField(
            model_name="tasubmission",
            old_name="elapsed_time4",
            new_name="taproblem4_elapsed_time",
        ),
        migrations.RenameField(
            model_name="tasubmission",
            old_name="elapsed_time5",
            new_name="taproblem5_elapsed_time",
        ),
        migrations.RenameField(
            model_name="tasubmission",
            old_name="elapsed_time6",
            new_name="taproblem6_elapsed_time",
        ),
        migrations.RenameField(
            model_name="tasubmission",
            old_name="elapsed_time7",
            new_name="taproblem7_elapsed_time",
        ),
    ]
