# Generated by Django 4.2.13 on 2024-08-03 03:52

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        (
            "home",
            "0027_rename_elapsed_time1_tasubmission_taproblem1_elapsed_time_and_more",
        ),
    ]

    operations = [
        migrations.CreateModel(
            name="TAFeedback",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("email", models.EmailField(max_length=254)),
                ("organisation", models.CharField(max_length=200)),
                ("designation", models.CharField(max_length=100)),
                ("ta_feedback1", models.CharField(max_length=10)),
                ("ta_feedback2", models.CharField(max_length=10)),
                ("ta_feedback3", models.CharField(max_length=10)),
                ("ta_feedback4", models.CharField(max_length=10)),
                ("ta_feedback5", models.CharField(max_length=10)),
                ("ta_feedback6", models.CharField(max_length=10)),
                ("ta_feedback7", models.CharField(max_length=10)),
                ("taproblem1_elapsed_time", models.IntegerField()),
                ("taproblem2_elapsed_time", models.IntegerField()),
                ("taproblem3_elapsed_time", models.IntegerField()),
                ("taproblem4_elapsed_time", models.IntegerField()),
                ("taproblem5_elapsed_time", models.IntegerField()),
                ("taproblem6_elapsed_time", models.IntegerField()),
                ("taproblem7_elapsed_time", models.IntegerField()),
            ],
        ),
        migrations.RemoveField(
            model_name="tasubmission",
            name="ta_feedback1",
        ),
        migrations.RemoveField(
            model_name="tasubmission",
            name="ta_feedback2",
        ),
        migrations.RemoveField(
            model_name="tasubmission",
            name="ta_feedback3",
        ),
        migrations.RemoveField(
            model_name="tasubmission",
            name="ta_feedback4",
        ),
        migrations.RemoveField(
            model_name="tasubmission",
            name="ta_feedback5",
        ),
        migrations.RemoveField(
            model_name="tasubmission",
            name="ta_feedback6",
        ),
        migrations.RemoveField(
            model_name="tasubmission",
            name="ta_feedback7",
        ),
        migrations.RemoveField(
            model_name="tasubmission",
            name="taproblem1_elapsed_time",
        ),
        migrations.RemoveField(
            model_name="tasubmission",
            name="taproblem2_elapsed_time",
        ),
        migrations.RemoveField(
            model_name="tasubmission",
            name="taproblem3_elapsed_time",
        ),
        migrations.RemoveField(
            model_name="tasubmission",
            name="taproblem4_elapsed_time",
        ),
        migrations.RemoveField(
            model_name="tasubmission",
            name="taproblem5_elapsed_time",
        ),
        migrations.RemoveField(
            model_name="tasubmission",
            name="taproblem6_elapsed_time",
        ),
        migrations.RemoveField(
            model_name="tasubmission",
            name="taproblem7_elapsed_time",
        ),
    ]
