# Generated by Django 4.2.13 on 2024-09-12 14:36

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("home", "0029_remove_tafeedback_designation_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="tasubmission",
            name="ta_logical_error_identification1",
        ),
        migrations.RemoveField(
            model_name="tasubmission",
            name="ta_logical_error_identification2",
        ),
        migrations.RemoveField(
            model_name="tasubmission",
            name="ta_logical_error_identification3",
        ),
        migrations.RemoveField(
            model_name="tasubmission",
            name="ta_logical_error_identification4",
        ),
        migrations.RemoveField(
            model_name="tasubmission",
            name="ta_logical_error_identification5",
        ),
        migrations.RemoveField(
            model_name="tasubmission",
            name="ta_logical_error_identification6",
        ),
        migrations.RemoveField(
            model_name="tasubmission",
            name="ta_logical_error_identification7",
        ),
        migrations.AddField(
            model_name="tasubmission",
            name="feedback1_rating",
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name="tasubmission",
            name="feedback2_rating",
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name="tasubmission",
            name="feedback3_rating",
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name="tasubmission",
            name="feedback4_rating",
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name="tasubmission",
            name="feedback5_rating",
            field=models.IntegerField(default=0),
        ),
    ]
