# Generated by Django 4.2.13 on 2024-09-12 19:00

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("home", "0032_remove_tasubmission_feedback34_rating_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="tasubmission",
            name="feedback54_rating",
        ),
        migrations.RemoveField(
            model_name="tasubmission",
            name="feedback55_rating",
        ),
        migrations.RemoveField(
            model_name="tasubmission",
            name="feedback74_rating",
        ),
        migrations.RemoveField(
            model_name="tasubmission",
            name="feedback75_rating",
        ),
    ]
