# Generated by Django 4.2.13 on 2024-09-13 10:48

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("home", "0034_tasubmission_feedback16_rating_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="StudyPhase",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("phase_name", models.CharField(max_length=20, unique=True)),
                ("is_active", models.BooleanField(default=False)),
            ],
        ),
    ]
