# Generated by Django 4.2.13 on 2024-09-13 10:57

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("home", "0036_remove_studyphase_is_active_and_more"),
    ]

    operations = [
        migrations.DeleteModel(
            name="StudyPhase",
        ),
    ]
