# Generated by Django 4.2.13 on 2024-09-24 16:14

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("home", "0037_delete_studyphase"),
    ]

    operations = [
        migrations.AlterField(
            model_name="tafeedback",
            name="id",
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
