# Generated by Django 4.2.13 on 2024-09-24 18:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("home", "0039_alter_tafeedback_id"),
    ]

    operations = [
        migrations.AlterField(
            model_name="tafeedback",
            name="ta_feedback1",
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name="tafeedback",
            name="ta_feedback2",
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name="tafeedback",
            name="ta_feedback3",
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name="tafeedback",
            name="ta_feedback4",
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name="tafeedback",
            name="ta_feedback5",
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name="tafeedback",
            name="ta_feedback6",
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name="tafeedback",
            name="ta_feedback7",
            field=models.TextField(),
        ),
        migrations.CreateModel(
            name="Feedbacks",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("problem_id", models.IntegerField()),
                ("content11", models.TextField()),
                ("content12", models.TextField()),
                ("content13", models.TextField()),
                ("content14", models.TextField()),
                ("content15", models.TextField()),
                ("content21", models.TextField()),
                ("content22", models.TextField()),
                ("content23", models.TextField()),
                ("content24", models.TextField()),
                ("content25", models.TextField()),
                ("content31", models.TextField()),
                ("content32", models.TextField()),
                ("content33", models.TextField()),
                ("content34", models.TextField()),
                ("content35", models.TextField()),
                ("content41", models.TextField()),
                ("content42", models.TextField()),
                ("content43", models.TextField()),
                ("content44", models.TextField()),
                ("content45", models.TextField()),
                ("content51", models.TextField()),
                ("content52", models.TextField()),
                ("content53", models.TextField()),
                ("content54", models.TextField()),
                ("content55", models.TextField()),
                ("content61", models.TextField()),
                ("content62", models.TextField()),
                ("content63", models.TextField()),
                ("content64", models.TextField()),
                ("content65", models.TextField()),
                ("content71", models.TextField()),
                ("content72", models.TextField()),
                ("content73", models.TextField()),
                ("content74", models.TextField()),
                ("content75", models.TextField()),
                (
                    "content16",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="feedback16_fk",
                        to="home.tafeedback",
                    ),
                ),
                (
                    "content17",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="feedback17_fk",
                        to="home.tafeedback",
                    ),
                ),
                (
                    "content26",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="feedback26_fk",
                        to="home.tafeedback",
                    ),
                ),
                (
                    "content27",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="feedback27_fk",
                        to="home.tafeedback",
                    ),
                ),
                (
                    "content36",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="feedback36_fk",
                        to="home.tafeedback",
                    ),
                ),
                (
                    "content37",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="feedback37_fk",
                        to="home.tafeedback",
                    ),
                ),
                (
                    "content46",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="feedback46_fk",
                        to="home.tafeedback",
                    ),
                ),
                (
                    "content47",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="feedback47_fk",
                        to="home.tafeedback",
                    ),
                ),
                (
                    "content56",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="feedback56_fk",
                        to="home.tafeedback",
                    ),
                ),
                (
                    "content57",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="feedback57_fk",
                        to="home.tafeedback",
                    ),
                ),
                (
                    "content66",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="feedback66_fk",
                        to="home.tafeedback",
                    ),
                ),
                (
                    "content67",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="feedback67_fk",
                        to="home.tafeedback",
                    ),
                ),
                (
                    "content76",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="feedback76_fk",
                        to="home.tafeedback",
                    ),
                ),
                (
                    "content77",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="feedback77_fk",
                        to="home.tafeedback",
                    ),
                ),
                (
                    "feedback",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="problem_feedbacks",
                        to="home.tafeedback",
                    ),
                ),
            ],
        ),
    ]
