# Generated by Django 4.2.13 on 2024-12-12 14:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("home", "0049_tafeedback_rollno_tasubmission_rollno_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="feedback",
            name="consent",
            field=models.CharField(default="Yes", max_length=10),
        ),
        migrations.AddField(
            model_name="tafeedback",
            name="consent",
            field=models.CharField(default="Yes", max_length=10),
        ),
        migrations.AddField(
            model_name="tasubmission",
            name="consent",
            field=models.CharField(default="Yes", max_length=10),
        ),
        migrations.AddField(
            model_name="usersubmission",
            name="consent",
            field=models.CharField(default="Yes", max_length=10),
        ),
    ]
