# Generated by Django 4.2.13 on 2025-01-04 13:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("home", "0050_feedback_consent_tafeedback_consent_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="Phase",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100, unique=True)),
                ("is_active", models.BooleanField(default=False)),
            ],
        ),
    ]
