# Generated by Django 4.2.13 on 2024-06-17 12:03

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("home", "0005_usersubmission_delete_participant_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="usersubmission",
            name="problem2_rating",
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="usersubmission",
            name="problem3_rating",
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="usersubmission",
            name="problem4_rating",
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="usersubmission",
            name="problem5_rating",
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="usersubmission",
            name="problem6_rating",
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="usersubmission",
            name="problem7_rating",
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
