# Generated by Django 4.2.13 on 2024-06-17 12:16

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("home", "0006_usersubmission_problem2_rating_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="usersubmission",
            name="problem4_rating",
        ),
        migrations.RemoveField(
            model_name="usersubmission",
            name="problem5_rating",
        ),
        migrations.RemoveField(
            model_name="usersubmission",
            name="problem6_rating",
        ),
        migrations.RemoveField(
            model_name="usersubmission",
            name="problem7_rating",
        ),
        migrations.AlterField(
            model_name="usersubmission",
            name="problem2_rating",
            field=models.CharField(max_length=5),
        ),
        migrations.AlterField(
            model_name="usersubmission",
            name="problem3_rating",
            field=models.CharField(max_length=5),
        ),
    ]
