# Generated by Django 4.2.13 on 2024-06-19 06:35

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("home", "0013_usersubmission_rating4_usersubmission_rating5_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="usersubmission",
            name="error_description_1",
            field=models.CharField(default=0, max_length=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="usersubmission",
            name="error_description_2",
            field=models.CharField(default=0, max_length=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="usersubmission",
            name="feedback_reveal",
            field=models.CharField(default=0, max_length=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="usersubmission",
            name="logical_error_identification",
            field=models.CharField(default=0, max_length=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="usersubmission",
            name="understandability",
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
