# Generated by Django 4.2.13 on 2024-06-19 06:37

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("home", "0014_usersubmission_error_description_1_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="usersubmission",
            name="rating",
        ),
    ]
