# Generated by Django 4.2.13 on 2024-07-29 04:12

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("home", "0019_tasubmission"),
    ]

    operations = [
        migrations.AddField(
            model_name="tasubmission",
            name="ta_logical_error_identification2",
            field=models.CharField(default=0, max_length=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="tasubmission",
            name="ta_logical_error_identification3",
            field=models.CharField(default=0, max_length=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="tasubmission",
            name="ta_logical_error_identification4",
            field=models.CharField(default=0, max_length=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="tasubmission",
            name="ta_logical_error_identification5",
            field=models.CharField(default=0, max_length=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="tasubmission",
            name="ta_logical_error_identification6",
            field=models.CharField(default=0, max_length=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="tasubmission",
            name="ta_logical_error_identification7",
            field=models.CharField(default=0, max_length=10),
            preserve_default=False,
        ),
    ]
