# Generated by Django 4.2.13 on 2024-07-31 15:25

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("home", "0025_rename_elapsed_time_tasubmission_elapsed_time1"),
    ]

    operations = [
        migrations.AddField(
            model_name="tasubmission",
            name="elapsed_time2",
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="tasubmission",
            name="elapsed_time3",
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="tasubmission",
            name="elapsed_time4",
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="tasubmission",
            name="elapsed_time5",
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="tasubmission",
            name="elapsed_time6",
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="tasubmission",
            name="elapsed_time7",
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
