# Generated by Django 4.2.13 on 2024-09-24 16:19

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("home", "0038_alter_tafeedback_id"),
    ]

    operations = [
        migrations.AlterField(
            model_name="tafeedback",
            name="id",
            field=models.BigAutoField(
                auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
            ),
        ),
    ]
