# Generated by Django 4.2.13 on 2024-09-24 18:09

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("home", "0041_rename_feedbacks_feedback"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="feedback",
            name="feedback",
        ),
    ]
