# Generated by Django 4.2.13 on 2024-09-25 11:11

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("home", "0044_remove_feedback_content6_remove_feedback_content7_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="tafeedback",
            name="feedbacks",
        ),
        migrations.AddField(
            model_name="feedback",
            name="content6",
            field=models.TextField(default="Test"),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="feedback",
            name="content7",
            field=models.TextField(default="Test2"),
            preserve_default=False,
        ),
    ]
