# Generated by Django 4.2.13 on 2024-10-03 18:15

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("home", "0047_remove_usersubmission_feedback_reveal1_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="feedback",
            name="content6",
        ),
        migrations.RemoveField(
            model_name="feedback",
            name="content7",
        ),
    ]
